# Generated by Django 4.2.2 on 2023-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_credit_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmerchant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmerchant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
