# Generated by Django 4.2.2 on 2023-07-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transactionmerchant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.transaction'),
        ),
    ]
