# Generated by Django 4.2.2 on 2023-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transaction_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
